apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: {{ .Values.name }}
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  replicas: {{ .Values.app.instances }}
  applicationImage: {{ .Values.repository }}:{{ .Values.app.version }}
  manageTLS: true
  expose: true
  {{- if .Values.app.env }}
  env:
  {{- range $key, $val := .Values.app.env }}
  - name: {{ $val.name | quote }}
    value:  {{ $val.value | quote }}
  {{- end }}
  {{- end }}
